package commandsToServer;

public enum UserCommand {

    EXIT_TO_AUTHORIZATION,
    GET_ALL_STATIONS,
    GET_TIME_TABLE,
    GET_ROUTE_STATIONS,
    GET_PASSENGERS,
    CREATE_PASSENGER,
    UPDATE_PASSENGER,
    DELETE_PASSENGER,
    CALCULATE_COST,
    CREATE_TICKET,
    PAY_TICKET,
    GET_ALL_TICKETS,
    GET_RULES,
    EDIT_PROFILE,
    GET_DOCUMENT_TYPES,

}
